# Generated by Django 3.1.3 on 2020-12-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cartAlbums',
            field=models.ManyToManyField(to='store.Album'),
        ),
    ]
