# Generated by Django 3.1.3 on 2020-12-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20201227_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cartAlbums',
            field=models.ManyToManyField(blank=True, null=True, to='store.Album'),
        ),
    ]
